#exposes the routes to allow traffic in and out
version: '3'
services:
  deployment:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
    volumes:
      - .:/app
      - /app/node_modules